version: "3"
services:
  postgres:
    container_name: clinicalsync-test-web-db
    image: lfd1/clinicalsync-test-web-db:latest
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test

volumes:
  db_data: ~